collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3476703
  brandStrength: 0.6684588
  lightness: 0.7795699
  rhythmicContrast: 0.749104
typography_spectrum: 0.4551971
layout_spectrum: 0.421147
name: Hw
